 title: Dream Come True
 subtitle: 现实梦想
 description: The Pursuit of Happyness
 author: 海天心Y2kking
 avatar: /images/avatar.png
 email: 182036669@qq.com #你的联系邮箱
 language: zh-Hans #语言包，需要主题自带才可设置。如Jcaman自带简繁英，设置简体中文填入 zh-CN
 timezone:

 # URL #这项暂不配置，绑定域名后，欲创建sitemap.xml需要配置该项
 ## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
 url: http://cometrue.top  #站点域名
 root: /
 permalink: :year/:month/:day/:title/  #文章永久链接格式，可添加.html后缀，如 :title.html
 permalink_defaults:

 # Directory
 source_dir: source
 public_dir: public
 tag_dir: tags
 archive_dir: archives
 category_dir: categories
 code_dir: downloads/code
 i18n_dir: :lang
 skip_render:
 
 # Writing
 new_post_name: :title.md # File name of new posts
 default_layout: post
 titlecase: false # Transform title into titlecase
 external_link: true # Open external links in new tab
 filename_case: 0
 render_drafts: false
 post_asset_folder: false
 relative_link: false
 future: true
 highlight:
   enable: true
   line_number: true
   auto_detect: false
   tab_replace:

 # Category & Tag
 default_category: uncategorized
 category_map:
 tag_map:

 # Date / Time format
 ## Hexo uses Moment.js to parse and display date
 ## You can customize the date format as defined in
 ## http://momentjs.com/docs/#/displaying/format/
 date_format: YYYY-MM-DD
 time_format: HH:mm:ss
 
 # Pagination
 ## Set per_page to 0 to disable pagination
 per_page: 10
 pagination_dir: page
 
 
 # Extensions  主题选择
 ## Plugins: https://hexo.io/plugins/
 ## Themes: https://hexo.io/themes/
 theme: next  #当前主题名称
 
 # Deployment
 ## Docs: https://hexo.io/docs/deployment.html
 deploy:
   type: git
   repo:
       github: git@github.com:yusmile/yusmile.github.io.git,master
       coding: git@git.coding.net:yusmile/yusmile.git,master    
       message: 'Daily updated：{{now("YYYY-MM-DD HH:mm:ss")}} by 海天心Y2kking personal PC'
 
 # 自己另外添加的功能
 #1.baidu_analytics
 baidu_analytics: 8759f43af3e04f8088e92ff251867945

 #2.站内搜索 Local Search  添加百度/谷歌/本地 自定义站点内容搜索。  需在站点的根目录下执行以下命令：$      npm install hexo-generator-searchdb --save
 search:
 path: search.xml
 field: post
 format: html
 limit: 10000

 #3.Feed 订阅
 feed: # 需安装插件：npm install hexo-generator-feed --save
   type: atom
   path: atom.xml
   limit: 20
   hub:    
 
 #4.自动生成sitemap  SEO推广,需执行以下命令，安装插件npm install hexo-generator-sitemap --save
 sitemap:
path: sitemap.xml
 baidusitemap:
    path: baidusitemap.xml  

  #5.内容分享服务
 # JiaThis 分享服务
 jiathis: true
 # 百度分享服务
 baidushare: true
 # 多说分享服务
 duoshuo_share: true
 duoshuo_hotartical: true  # 多说热评文章 true 或者 false
 duoshuo_shortname: yusmile
 # Disqus Disqus插件，如果使用的话
 #disqus_shortname:
